version: '3.8'

services:
  sdr-ia-app:
    # --- MUDANÇA PRINCIPAL ---
    # Removido o bloco "build:".
    # Substituído por "image:", que aponta para a imagem que VOCÊ VAI construir e enviar para o Docker Hub.
    # Use o nome do seu repositório do GitHub para manter a consistência.
    image: SEU-USUARIO-DOCKERHUB/sdr-ia-app-ofc:1.0

    container_name: sdr_ia_app
    restart: unless-stopped
    ports:
      # Mapeia a porta 5000 do seu servidor para a porta 5000 da aplicação.
      # Você poderá acessar sua app em http://IP_DO_SEU_SERVIDOR:5000
      - "5000:5000"
    environment:
      # É uma boa prática definir suas variáveis aqui.
      - SECRET_KEY=troque-por-uma-chave-secreta-muito-longa-e-segura
      - FLASK_ENV=production
    volumes:
      # O volume para o banco de dados está perfeito para persistir os dados.
      - sdr_ia_data:/app/database

    # As labels do Traefik são para um reverse proxy. Se você não usa Traefik,
    # pode remover todo este bloco "labels:". Se usa, garanta que seu domínio está correto.
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.sdr-ia.rule=Host(`sua-url.com`)"
      - "traefik.http.routers.sdr-ia.entrypoints=websecure"
      - "traefik.http.routers.sdr-ia.tls.certresolver=letsencrypt"
      - "traefik.http.services.sdr-ia.loadbalancer.server.port=5000"

  # Serviço opcional de backup do banco de dados
  backup:
    image: alpine:latest
    container_name: sdr_ia_backup
    volumes:
      - sdr_ia_data:/data:ro
      - ./backups:/backups
    command: >
      sh -c "
        mkdir -p /backups &&
        tar -czf /backups/sdr_ia_backup_$$(date +%Y%m%d_%H%M%S).tar.gz -C /data . &&
        find /backups -name '*.tar.gz' -mtime +7 -delete
      "
    # --- CORREÇÃO DO ERRO ANTERIOR ---
    # A propriedade "profiles:" foi removida para evitar o erro de sintaxe.
    # Você pode rodar este serviço manualmente pelo Portainer se precisar de um backup.

volumes:
  sdr_ia_data:
    driver: local

# A rede não é estritamente necessária para um único serviço, mas é uma boa prática.
# Removi para simplificar, mas você pode adicionar de volta se precisar.
