version: '3.8'

services:
  app:
    image: python:3.11-slim
    working_dir: /app
    command: >
      sh -c "
        apt-get update && apt-get install -y gcc curl &&
        pip install --no-cache-dir -r requirements.txt &&
        mkdir -p src/database logs &&
        python src/main.py
      "
    ports:
      - "5000:5000"
    environment:
      # Variáveis obrigatórias - DEFINIR NO PORTAINER
      - SECRET_KEY=sdr-ia-secret-key-change-in-production-123456789
      - OPENAI_API_KEY=sua-chave-openai-aqui
      
      # Variáveis opcionais
      - N8N_BASE_URL=
      - N8N_API_KEY=
      - APP_BASE_URL=https://sdria.alveseco.com.br
      
      # Configurações Flask
      - FLASK_ENV=production
      - FLASK_DEBUG=false
      - PYTHONUNBUFFERED=1
      - PORT=5000
      
    volumes:
      # Volume persistente para banco de dados
      - sdr_ia_data:/app/src/database
      # Volume para logs (opcional)
      - sdr_ia_logs:/app/logs
      # Mapear código fonte
      - .:/app
      
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
      resources:
        limits:
          memory: 1G
        reservations:
          memory: 512M

volumes:
  sdr_ia_data:
    driver: local
  sdr_ia_logs:
    driver: local
